# Generated by Django 3.1.12 on 2025-04-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20250407_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='module_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
