# Generated by Django 3.1.12 on 2025-04-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_auto_20250407_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='module_description',
        ),
        migrations.AddField(
            model_name='chapter',
            name='module_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
