# Generated by Django 3.1.12 on 2025-04-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_auto_20250407_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='module_description',
            new_name='chapter_description',
        ),
    ]
