# Generated by Django 3.1.12 on 2025-04-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_mocktest_mocktestquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
