# Generated by Django 3.1.12 on 2025-04-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_auto_20250415_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_chapters',
            field=models.IntegerField(default=0),
        ),
    ]
