# Generated by Django 3.1.12 on 2025-04-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_course_total_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_quizzes',
            field=models.IntegerField(default=0),
        ),
    ]
