# Generated by Django 3.1.12 on 2025-05-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_course_total_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='total_chapters',
            field=models.IntegerField(default=0),
        ),
    ]
