from django.urls import path
from .views import (
    AdminLoginView, LandingMediaUploadView, LandingMediaListView, LandingMediaDeleteView,
    GalleryImageUploadView, GalleryImageListView, GalleryImageDeleteView,
    CourseCreateView, ModuleCreateView, ChapterCreateView, QuizCreateView,
    CourseListView, CourseDetailView, ModuleDetailView, ChapterDetailView, QuizDetailView,
    RecommendedCoursesView, RecommendCourseView, CourseUpdateView, ModuleDeleteView,
    ChapterUpdateView, ChapterDeleteView, QuizUpdateView, QuizDeleteView, CourseDeleteView,
    EventCreateView, EventListView, EventDeleteView, MockTestCreateView, MockTestListView, MockTestDeleteView,
    MockTestQuizCreateView, MockTestQuizDeleteView, CourseMetaAPIView, StudentListView, StudentDetailView,
    AuthorCreateView, AuthorListView, AuthorDetailView, AuthorUpdateView, AuthorByCourseView,
    CourseSearchView,
)

urlpatterns = [
    path('login/', AdminLoginView.as_view(), name='admin-login'),
    path('media/upload/', LandingMediaUploadView.as_view(), name='media-upload'),
    path('media/list/', LandingMediaListView.as_view(), name='media-list'),
    path('media/delete/<int:pk>/', LandingMediaDeleteView.as_view(), name='media-delete'),
    path('gallery/upload/', GalleryImageUploadView.as_view(), name='gallery-upload'),
    path('gallery/', GalleryImageListView.as_view(), name='gallery-list'),
    path('gallery/<int:pk>/', GalleryImageDeleteView.as_view(), name='gallery-delete'),
    path('courses/create/', CourseCreateView.as_view(), name='course-create'),
    path('courses/', CourseListView.as_view(), name='course-list'),
    path('courses/<int:id>/', CourseDetailView.as_view(), name='course-detail'),
    path('courses/recommended/', RecommendedCoursesView.as_view(), name='recommended-courses'),
    path('courses/<int:course_id>/recommend/', RecommendCourseView.as_view(), name='recommend-course'),
    path('courses/<int:course_id>/modules/create/', ModuleCreateView.as_view(), name='module-create'),
    path('modules/<int:id>/', ModuleDetailView.as_view(), name='module-detail'),
    path('modules/<int:module_id>/chapters/create/', ChapterCreateView.as_view(), name='chapter-create'),
    path('chapters/<int:id>/', ChapterDetailView.as_view(), name='chapter-detail'),
    path('chapters/<int:chapter_id>/quizzes/create/', QuizCreateView.as_view(), name='quiz-create'),
    path('quizzes/<int:id>/', QuizDetailView.as_view(), name='quiz-detail'),
    path('courses/<int:id>/update/', CourseUpdateView.as_view(), name='course-update'),
    path('modules/<int:id>/delete/', ModuleDeleteView.as_view(), name='module-delete'),
    path('chapters/<int:id>/update/', ChapterUpdateView.as_view(), name='chapter-update'),
    path('chapters/<int:id>/delete/', ChapterDeleteView.as_view(), name='chapter-delete'),
    path('quizzes/<int:id>/update/', QuizUpdateView.as_view(), name='quiz-update'),
    path('quizzes/<int:id>/delete/', QuizDeleteView.as_view(), name='quiz-delete'),
    path('courses/<int:id>/delete/', CourseDeleteView.as_view(), name='course-delete'),
    path('events/create/', EventCreateView.as_view(), name='event-create'),
    path('events/', EventListView.as_view(), name='event-list'),
    path('events/<int:id>/delete/', EventDeleteView.as_view(), name='event-delete'),
    path('mocktests/create/', MockTestCreateView.as_view(), name='mocktest-create'),
    path('mocktests/', MockTestListView.as_view(), name='mocktest-list'),
    path('mocktests/<int:id>/delete/', MockTestDeleteView.as_view(), name='mocktest-delete'),
    path('mocktests/<int:mock_test>/quizzes/create/', MockTestQuizCreateView.as_view(), name='mocktest-quiz-create'),
    path('mocktests/quizzes/<int:id>/delete/', MockTestQuizDeleteView.as_view(), name='mocktest-quiz-delete'),
    path('course-meta/<int:id>/', CourseMetaAPIView.as_view(), name='course-meta'),
    path('students/', StudentListView.as_view(), name='student-list'),
    path('students/<int:student_id>/', StudentDetailView.as_view(), name='student-detail'),
    path('authors/create/', AuthorCreateView.as_view(), name='author-create'),
    path('authors/', AuthorListView.as_view(), name='author-list'),
    path('authors/<int:id>/', AuthorDetailView.as_view(), name='author-detail'),
    path('authors/<int:id>/update/', AuthorUpdateView.as_view(), name='author-update'),
    path('courses/<int:course_id>/author/', AuthorByCourseView.as_view(), name='author-by-course'),
    path('courses/search/', CourseSearchView.as_view(), name='course-search'),
]