# Generated by Django 3.1.12 on 2025-04-25 09:01

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20250425_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='chapter_status',
            field=djongo.models.fields.JSONField(default=dict),
        ),
    ]
