# Generated by Django 3.1.12 on 2025-04-25 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_course_total_quizzes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0003_courseprogress_chapter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='chapter_status',
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='completed_quizzes',
            field=djongo.models.fields.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='admin_panel.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz'], name='student_qui_user_id_08b071_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('user', 'quiz')},
        ),
    ]
