# Generated by Django 3.1.12 on 2025-04-26 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_course_total_quizzes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0004_auto_20250425_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', djongo.models.fields.JSONField(default=list)),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='admin_panel.mocktest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['user', 'mock_test'], name='student_moc_user_id_204469_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mocktestattempt',
            unique_together={('user', 'mock_test')},
        ),
    ]
